services:
  - type: web
    name: dashboard-market-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: False
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: DATA_DIR
        value: ./us_market/data
